apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1
  labels:
    name: node-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      name: node-app1
      labels:
        app: node-app1
    spec:
      containers:
        - name: node-app1
          image: akib123/node-app1:v1.0
          imagePullPolicy: IfNotPresent
      nodeSelector:
          app: app1
     
---
apiVersion: v1 
kind: Service
metadata: 
  name: node-app1
spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30008
  selector:
    app: node-app1
    
