pipeline {
    agent any
    stages{
        //Automatically it will checkout scm, so no worries
stage('Test') {
               steps{
                 //   git https://github.com/akibhasan15/Node-Hello-World
                   
                   nodejs(nodeJSInstallationName: 'nodejs'){
                    sh 'cd ./app1/src/ && npm install'
                    //Every time any shell command or anything executed, it throw me on parent directory
                    // found in /var/jenkins_home/workspace/node-app1/
                    sh 'cd ./app1/src/ && ls -la'
                    //sh 'npm test'
                    
                   }
}
} 
stage('Build') {

    steps{
           sh 'docker build -t akib123/node-app1:v1.0 -f ./app1/build/Dockerfile ./app1/src/'
           
    }
} 
 stage('Deployment') {
           
            steps{
                 
               sshagent(credentials: ['illusion']) {
               withCredentials([string(credentialsId: 'USER@KubeServer', variable: 'userAtIP')]) {
    // some block
                sh 'scp ./app1/deploy/app1.yaml   ${userAtIP}:Desktop/ '
}
               
               
               sh 'ssh illusion@172.17.0.1 "minikube kubectl -- apply -f Desktop/app1.yaml"' 

    }
            }
    }
} 

}

