pipeline {
    agent any
    stages{
        
stage('test') {
               steps{
                 //   git https://github.com/akibhasan15/Node-Hello-World
                   
                   nodejs(nodeJSInstallationName: 'nodejs'){
                    sh 'cd ./app1/src/'
                    //sh 'npm install'
                    sh 'ls -la'
                    //sh 'npm test'
                    sh 'cd ../../'
                   }
}



    }
} }
