apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2
  labels:
    name: node-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      name: node-app2
      labels:
        app: node-app2
    spec:
      containers:
        - name: node-app2
          image: akib123/node-app2:v1.0
          imagePullPolicy: IfNotPresent
      nodeSelector:
        app: app2
     
---
apiVersion: v1 
kind: Service
metadata: 
  name: node-app2
spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30009
  selector:
    app: node-app2
---
